
const homedata = [
    {
      id: 1,
      emoji: "💪",
      name: "event1",
      instructions:
        "TrashBot is an event to exhibit one's creativity. The participants should design and prepare a model of a robot out of trash. Participants are expected to build robots for high utilities using as much trash as possible. ",
        instructions2:"",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Trash Bot",
        submission1:"Submission platform- Google Forms ",
        submission2:"The submission window will be open from 12:01 am, 18/03/2022 to 11.59 p.m, 23/03/2022",
        judging1:"The participants will be judged based on their creativity and innovation; amount of trash material used along with the utilities of the robot model built by them. ",
        judging2:"",
        judging3:"",
        prerequisites:"All you need is just creativity and basic knowledge of high school physics. ",
        prizes:"",
        image:"../../assets/images/trash-bot.jpeg",
        srcDoc:"https://docs.google.com/document/d/1bcbX724b5yt1HKjAwL8YXA_LZjDtLBItEwg_GpsE0QY/edit"
    },
    {
      id: 2,
      emoji: "🙏",
      name: "event2",
      instructions:
        "So as to encourage women participation in the field of programming ,we Robotics Society is going to organise a coding competition for female participants in RoboWeek 2.0  in  which they will be given some amazing problem statements to solve so as to showcase their coding and problem solving skills .",
        instructions2:"",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Code Naari",
        submission1:"The contest will be live on 25th March 2022 from TBD – TBD IST. The contest’s duration is 3 hours.",
        submission2:"",
        judging1:"",
        judging2:"",
        judging3:"",
        prerequisites:" Any female student who is currently pursuing any undergraduate degree ",
        prizes:"",

        image:"../../assets/images/code-nari.jpeg",

        srcDoc:"https://docs.google.com/document/d/1JGfo0aMb4-PgUhfJbD9WTiXHpmcqb_b6OomciORBkUg/edit?usp=sharing"
    },
    {
      id: 3,
      emoji: "🤣",
      name: "event3",
      instructions: " Bringing you the enigma of words and expressions, Roboweek presents you the technical writing competition “Callisto: words for thoughts “.  A battle of pens curated to spark the cells in your brain and force you to think about the odds. The goal is to bring out the best of your expressions in words.        Entrants will be given 3 different problem statements, from which they can opt for anyone. Mind nothing is wrong, nothing is right, provided any part of your submission is not plagiarised and doesn't exceed 400 words. Put the essence of your imagination into vocables and you are good to go.Get ready to reflect yourself into your writing and there’s a lot awaiting you on the other side.",
      instructions2:" 1 round only",
      instructions3:"",
      instructions4:"",
        instructions5:"",
        title:" Callisto",
        submission1:"Statement release - 17:00, 22/03/2022",
        submission2:"Submission Window - 24/03(00:00) - 25/03(23:59)",
        judging1:"Plagiarism will not be entertained",
        judging2:"Submissions will be marked on the basis of creativity, use of words, originality.",
        judging3:"",
        prerequisites:" Anyone pursuing an undergraduate degree can participate.",
        prizes:"",
        image:"../../assets/images/callisto.jpg",
        srcDoc:"https://docs.google.com/document/d/1bCZdxce2AydavlmnKfiYLxCHGY2Y6rJ29zaFXpD4htw/edit?usp=sharing"
    },
    {
      id: 4,
      emoji: "🤣",
      name: "event4",
      instructions:
        "Hunt-Nova is a mind boggling contest where you can play with your logic to crack the components and build a working prototype on TinkerCad.",
        instructions2:"",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"HUNT NOVA",
        submission1:"Problem Statement Release  on 21/03/2022  at 5 PM IST.",
        submission2:"Submission Window Close  on 23/03/2022 at 11:59 PM IST.",
        judging1:"1.Working on the  project.",
        judging2:"2.Neatness of circuit.",
        judging3:"3.Components used if any extra component is used then marks will be deducted.",
        prerequisites:"TinkerCad and Circuit designing.",
        prizes:"",
        image:"../../assets/images/hunt-nova.jpg",
        srcDoc:"https://docs.google.com/document/d/1Rnd--W0dzLetZZ2oOkA5ik4wcBjy5c6JEbCTZE7xVVw/edit?usp=sharing"
    }
    ,
    {
      id: 5,
      emoji: "🤣",
      name: "event7",
      instructions:
        "Code-Play is a coding competition where participants have to solve a given set of problems in a fixed amount of time. ",
        instructions2:"The competition will consist of only one round. ",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Code play",
        submission1:"The contest will begin on 21/03/2022 at (TBD) IST.",
        submission2:"The contest will end on 21/03/2022 at (TBD) IST.",
        judging1:"Individuals will be ranked as per the number of problems solved.",
        judging2:"",
        judging3:"",
        prerequisites:"This contest is open to anyone who likes programming. ",
        prizes:"",
        image:"../../assets/images/code-play.png",
        srcDoc:"https://docs.google.com/document/d/1aKmJqsTtZxFZKgHvRXXhNojta7za_YROfL3wtrmXbkM/edit?usp=sharing"
    } ,
    {
      id: 6,
      emoji: "🤣",
      name: "event8",
      instructions:
        "In this version of Design Wars 2.0, participants have to design any thing related to the problem statement.Student are required to create designs by using the designing softwares such as AutoCAD, OnShape, Solidworks and Fusion 360.  Problem statement will be out on 18th March.",
        instructions2:"Contest comprises of two rounds :",
        instructions3:"Round 1 : In Round 1 participants have to submit their design based on the problem statement before the deadline. After the deadline, no submission will be considered.",
        instructions4:" Round 2: Top performers of Round 1 would be selected for the interview round where they have to answer the questions asked by the interview panel. Questions will be based on the design which they have submitted in Round 1. Participants should have knowledge about the working and applications of the submitted design.",
        instructions5:"",
        title:"Design wars",
        submission1:"Link will be shared along with the problem statement",
        submission2:"",
        judging1:"Scoring would be done on the basis of proper dimensioning of sketches, number of components used, rendering effects, use of complex mechanisms and assemblies, etc. Bonus marks would be provided if Animation, Simulations and Dynamic Study is provided.",
        judging2:"",
        judging3:"",
        prerequisites:"Students from all the degree programs and years are eligible to participate in this competition.",
        prizes:"Top 3 performers of round 2 will be awarded with prizes.",
        image:"../../assets/images/design-wars.png",
        srcDoc:"https://docs.google.com/document/d/1sQhRUUaS18pYQ_mnIwJ6eXvWiynF_Xk18S0TGSCupdU/edit"
    } ,
    {
      id: 7,
      emoji: "🤣",
      name: "event9",
      instructions:
        "In this version of Regatta 2.0, participants have to solve the problem statements  using ROS or constructsim(online).  Problem statements will be released on 18th March",

        instructions2:"1 Round only.",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Regetta",
        submission1:"Statement release-18/03(17:00)",
        submission2:"Submission window-23/03(00:00) - 24/03(23:59)",
        submission2:"All files are needed to be sumbitted via a private github repo. Further details would be revealed with the problem statement. ",
        judging1:"Based on performance in indvidual problems, Full score distribution would be in problem statement.",
        judging2:"In case of tie breaker star marked problems would be given preference. ",
        judging3:"If above not applies participants would be judged on cleanliness and readability of code full decision is in the hands of organising team.",

        prerequisites:"Python/C++ programming  and Basic ROS",
        prizes:"",
        image:"../../assets/images/REGATTA.png",
        srcDoc:"https://docs.google.com/document/d/1MFIrG2QMHhVTAYFjRv1T-4p5Hw6_vB3Lya75SxpYA5U/edit"
    } ,
    {
      id: 8,
      emoji: "🤣",
      name: "event5",
      instructions:
        "In this event you will be given some topics, on which you have to make a 7- 10 minute video in one week. A library containing stock videos and images will be provided. You also have to submit a word file explaining the essence, transition and edits of your video that you made. Also the links of videos used if you are using something outside of the library we provided.",
        instructions2:"",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"#Clipped",
        submission1:"List of Topics will be released  on 18/03/2022  at 5 PM IST.",
        submission2:"Submission Window will open from 24/03 at 00:00  to 25/03 at 23:59",
        judging1:"Influence and feel- How they manage to influence and motivate the viewers about robotics.",
        judging2:"Quality of post-production - 1. Transition between clips   2. Color Correction 3. Use of Music  4. Attention to detail",
        judging3:"",
        prerequisites:"Any student can take part.",
        prizes:"",
        image:"../../assets/images/clipped.jpg",
        srcDoc:"https://docs.google.com/document/d/1nR2BA9EprOUfOUkP5l3lO6a7gnBiV9-kBqSxbpDf7xs/edit?usp=sharing"
    } ,
    {
      id: 9,
      emoji: "🤣",
      name: "event6",
      instructions:
        "The players have to decode the hints and ciphers (further hints may be present on different pages across the internet) and enter the answers for each level. The first one to clear all the levels will be declared the winner.",
        instructions2:"The first one to clear all the levels will be declared as the winner. Players who finish after this, shall be ranked consecutively In case of any issue or dispute, decisions of the organizers will be final and binding. No claim will be entertained against the announced results.",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Arcanum ",
        submission1:"The event will be held from 12.01 a.m, 20/03/2022 to 11.59 p.m, 20/03/2022 ",
        submission2:"",
        judging1:"Your username should be '<name>_<rollno>_<college>'. ",
        judging2:"It is an individual event, only lone wolves allowed.",
        judging3:" You will be directed to the next question when you type the correct answer to the current question.",
        prerequisites:"All college students",
        prizes:"",
        image:"../../assets/images/Arcanum.png",
        srcDoc:"https://docs.google.com/document/d/1Yia0B1RrDKRsKUPnsl1lTE5s_DJae3MqvAXq_Anid2o/edit?usp=sharing"
    },
    {
      id: 10,
      emoji: "🤣",
      name: "event10",
      instructions:
        "Tinker It is an IOT challenge where the participants need to demonstrate their grasp and understanding of basic IOT by solving a variety of challenge statements.",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Tinker It",
        submission1:" The problem statements will be released on 9:00 p.m, 21/03/2022.",
        submission2:"",
        judging1:"The participants will be judged based on the number of problem statements solved by them, the efficiency of code and circuitry along with any unique ideas incorporated in the solutions by them.",
        judging2:"The submission window will be open from 12:01 am, 22/03/2022 to 11.59 p.m, 22/03/2022. ",
        judging3:" ",
        prerequisites:"All B.Tech. students of first and second year.",
        prizes:"",
        image:"../../assets/images/Tinker_ It.png",
        srcDoc:"https://docs.google.com/document/d/1Yia0B1RrDKRsKUPnsl1lTE5s_DJae3MqvAXq_Anid2o/edit?usp=sharing"
    }
     
    
  ];
  
  
  export default homedata