
const homedata = [
    {
      id: 1,
      emoji: "💪",
      name: "trashbot",
      instructions:
        "TrashBot is an event to exhibit one's creativity. ",
        instructions2:" The participants should design and prepare a model of a robot out of trash.",
        instructions3:"Participants are expected to build robots for high utilities using as much trash as possible. ",
        
       
        title:"Trash Bot",
        submission1:"Submission platform- Google Forms ",
        submission2:"The submission window will be open from 12:01 am, 18/03/2022 to 11.59 p.m, 23/03/2022",
        judging1:"The participants will be judged based on their creativity and innovation; ",
        judging2:" Amount of trash material used along with the utilities of the robot model built by them.",
        judging3:"",
        prerequisites:"All you need is just creativity and basic knowledge of high school physics. ",
        prizes:"TBD",
        image:"../../assets/images/trash-bot.png",
        srcDoc:"https://docs.google.com/document/d/1bcbX724b5yt1HKjAwL8YXA_LZjDtLBItEwg_GpsE0QY/edit",
        srcReg:"https://dare2compete.com/competition/trash-bot-roboweek-20-national-institute-of-technology-nit-hamirpur-263560"
    },
    {
      id: 2,
      emoji: "🙏",
      name: "codenaari",
      instructions:
        "To encourage women participation in the field of programming .",
        instructions2:"We Robotics Society is going to organise a coding competition for female participants in RoboWeek 2.0 ",
        instructions3:" They will be given some amazing problem statements to showcase their coding and problem solving skills .",
        instructions4:"",
        instructions5:"",
        title:"Code Naari",
        submission1:"Submission platform- TBD",
        submission2:"The submission window will be open from TBD am, TBD to TBD p.m, TBD",
        judging1:"Individuals will be ranked as per the number of problems solved.",
        judging2:"The participants will be judged based on their creativity",
        judging3:"",
        prerequisites:" Any female student who is currently pursuing any undergraduate degree ",
        prizes:"TBD",

        image:"../../assets/images/code-nari.jpeg",

        srcDoc:"https://docs.google.com/document/d/1JGfo0aMb4-PgUhfJbD9WTiXHpmcqb_b6OomciORBkUg/edit?usp=sharing",
        srcReg:"https://dare2compete.com/hackathon/code-naari-roboweek-20-national-institute-of-technology-nit-hamirpur-263649"
    },
    {
      id: 3,
      emoji: "🤣",
      name: "callisto",
      instructions: " Bringing you the enigma of words and expressions, Roboweek presents you the technical writing competition .",
      instructions2:"A battle of pens curated to spark the cells in your brain and force you to think about the odds.",
      instructions3:"The goal is to bring out the best of your expressions in words.",
        title:" Callisto",
        submission1:"Submission platform- TBD",
        submission2:"The submission window will be open from 24/03(00:00) to 25/03(23:59)",
        judging1:"Plagiarism will not be entertained",
        judging2:"Submissions will be marked on the basis of creativity, use of words, originality.",
        judging3:"",
        prerequisites:" Anyone pursuing an undergraduate degree can participate.",
        prizes:"TBD",
        image:"../../assets/images/callisto.jpg",
        srcDoc:"https://docs.google.com/document/d/1bCZdxce2AydavlmnKfiYLxCHGY2Y6rJ29zaFXpD4htw/edit?usp=sharing",
        srcReg:"https://dare2compete.com/creative-cultural-event/callisto-roboweek-20-national-institute-of-technology-nit-hamirpur-263270"
    },
    {
      id: 4,
      emoji: "🤣",
      name: "huntnova",
      instructions:
        "Hunt-Nova is a mind boggling contest where you can play with your logics,",
        instructions2:"Crack the components and build a working prototype on TinkerCad.",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Hunt Nova",
        submission1:"Submission platform- TBD",
        submission2:"The submission window will be open from  5 P.M. , 21/03/2022 to 11.59 P.M , 23/03/2022",
        judging1:"Working of the project",
        judging2:"The neatness of the circuit",
        judging3:"Components used if any extra component is used then marks will be deducted.",
        prerequisites:"TinkerCad and Circuit designing.",
        prizes:"TBD",
        image:"../../assets/images/hunt-nova-2.png",
        srcDoc:"https://docs.google.com/document/d/1Rnd--W0dzLetZZ2oOkA5ik4wcBjy5c6JEbCTZE7xVVw/edit?usp=sharing",
        srcReg:"https://dare2compete.com/competition/hunt-nova-roboweek-20-national-institute-of-technology-nit-hamirpur-263565"
    }
    ,
    {
      id: 5,
      emoji: "🤣",
      name: "codeplay",
      instructions:
        "Coding competition to solve a given set of problems in a fixed amount of time. ",
        instructions2:"The competition will consist of only one round. ",
        instructions3:"compete with many coders from around the country.",
        instructions4:"",
        instructions5:"",
        title:"Code play",
        submission1:"Submission platform- TBD",
        submission2:"The submission window will be open from TBD am, 21/03/2022 to TBD p.m, 21/03/2022",
        judging1:"Individuals will be ranked as per the number of problems solved.",
        judging2:"The compiler supports all 3 majorly popular programming languages C++, Java, Python.",
        prerequisites:"This contest is open to anyone who likes programming. ",
        prizes:"TBD",
        image:"../../assets/images/code-play.png",
        srcDoc:"https://docs.google.com/document/d/1aKmJqsTtZxFZKgHvRXXhNojta7za_YROfL3wtrmXbkM/edit?usp=sharing",
        srcReg:"https://dare2compete.com/hackathon/code-play-roboweek-20-national-institute-of-technology-nit-hamirpur-263922"
    } ,
    {
      id: 6,
      emoji: "🤣",
      name: "designwars",
      instructions:
        "Participants have to design any thing related to the problem statement.",
        instructions2:"Create designs by using the designing softwares such as AutoCAD, OnShape, Solidworks and Fusion 360.",
        instructions3:"Problem statement will be out on 18th March.Contest comprises of two rounds",
        instructions4:"",
        instructions5:"",
        title:"Design wars 2.0",
        submission1:"Submission platform- TBD",
        submission2:"The submission window will be open from TBD am, TBD to TBD p.m, TBD",
        judging1:"Scoring would be done on the basis of proper dimensioning of sketches, number of components used, ",
        judging2:"rendering effects, use of complex mechanisms and assemblies, etc.",
        judging3:"Bonus marks would be provided if Animation, Simulations and Dynamic Study is provided.",
        prerequisites:"Students from all the degree programs and years are eligible to participate in this competition.",
        prizes:"Top 3 performers of round 2 will be awarded with prizes.",
        image:"../../assets/images/design-wars.png",
        srcDoc:"https://docs.google.com/document/d/1sQhRUUaS18pYQ_mnIwJ6eXvWiynF_Xk18S0TGSCupdU/edit",
        srcReg:"https://dare2compete.com/creative-cultural-event/design-wars-20-roboweek-20-national-institute-of-technology-nit-hamirpur-263524"
    } ,
    {
      id: 7,
      emoji: "🤣",
      name: "regatta",
      instructions:
        "Participants have to solve the problem statements  using ROS or constructsim(online).",

        instructions2:"Eye opener and way to propagate the importance of ROS amongst enthusiasts",
        instructions3:"",
        instructions4:"",
        instructions5:"",
        title:"Regetta 2.0",
        submission1:"Submission platform- TBD. Statement release-18/03(17:00)",
        submission2:"The submission window will be open from 23/03(00:00) to 23/03(00:00)",
        submission3:"All files are needed to be sumbitted via a private github repo.",
        judging1:"Full score distribution would be in problem statement.",
        judging2:"In case of tie breaker star marked problems would be given preference. ",
        judging3:"If above not applies participants would be judged on cleanliness and readability of code ",

        prerequisites:"Python/C++ programming  and Basic ROS",
        prizes:"TBD",
        image:"../../assets/images/REGATTA.png",
        srcDoc:"https://docs.google.com/document/d/1MFIrG2QMHhVTAYFjRv1T-4p5Hw6_vB3Lya75SxpYA5U/edit",
        srcReg:"https://dare2compete.com/competition/regatta-20-roboweek-20-national-institute-of-technology-nit-hamirpur-263326"
    } ,
    {
      id: 8,
      emoji: "🤣",
      name: "clipped",
      instructions:
        "You will be given some topics, on which you have to make a 7- 10 minute video in one week.",
        instructions2:"Submit a word file explaining the essence, transition and edits of your video that you made.",
        instructions3:"Also the links of videos used if you are using something outside of the library we provided.",
        instructions4:"",
        instructions5:"",
        title:"#Clipped",
        submission1:"Submission platform- TBD. Statement release-18/03/2022  at 5 PM IST.",
        submission2:"The submission window will be open from 24/03 at 00:00  to 25/03 at 23:59.",
        judging1:"How they manage to influence and motivate the viewers about robotics.",
        judging2:"Quality of post-production, Transition between clips, Color Correction, Use of Music and Attention to detail.",
        judging3:"",
        prerequisites:"Any student can take part.",
        prizes:"TBD",
        image:"../../assets/images/clipped.jpg",
        srcDoc:"https://docs.google.com/document/d/1nR2BA9EprOUfOUkP5l3lO6a7gnBiV9-kBqSxbpDf7xs/edit?usp=sharing",
        srcReg:"https://dare2compete.com/creative-cultural-event/clipped-roboweek-20-national-institute-of-technology-nit-hamirpur-263537"
    } ,
    {
      id: 9,
      emoji: "🤣",
      name: "arcanum",
      instructions:
        "The players have to Decode the hints and ciphers and enter the answers for each level.",
        instructions2:"The first one to clear all the levels will be declared as the winner. ",
        instructions3:"Players who finish after this, shall be ranked consecutively.",
        instructions4:"",
        instructions5:"",
        title:"Arcanum ",
        submission1:"Submission platform- TBD.",
        submission2:"The submission window will be open from 12.01 a.m, 20/03/2022 to 11.59 p.m, 20/03/2022 ",
        judging1:" You will be directed to the next question when you type the correct answer to the current question.",
        judging2:"It is an individual event, only lone wolves allowed.",
        judging3:"",
        prerequisites:"All college students",
        prizes:"TBD",
        image:"../../assets/images/Arcanum.png",
        srcDoc:"https://docs.google.com/document/d/1Yia0B1RrDKRsKUPnsl1lTE5s_DJae3MqvAXq_Anid2o/edit?usp=sharing",
        srcReg:"https://dare2compete.com/competition/arcanum-roboweek-20-national-institute-of-technology-nit-hamirpur-263309"
    },
    {
      id: 10,
      emoji: "🤣",
      name: "tinkerit",
      instructions:
        "Tinker It is an IOT challenge where the participants need to demonstrate their grasp.",
        instructions2:"Understanding of basic IOT by solving a variety of challenge statements.",
        instructions3:"Participants need to solve as many problem statements as they can during the submission window",
        instructions4:"",
        title:"Tinker It",
        submission1:"Submission platform- TinkerCAD links in the google forms provided. Statement release-9:00 p.m, 21/03/2022",
        submission2:"The submission window will be open from 12:01 am, 22/03/2022 to 11.59 p.m, 22/03/2022",
        judging1:"The participants will be judged based on the number of problem statements solved by them",
        judging2:"The submission window will be open from 12:01 am, 22/03/2022 to 11.59 p.m, 22/03/2022. ",
        judging3:"The efficiency of code and circuitry along with any unique ideas incorporated in the solutions by them ",
        prerequisites:"All B.Tech. students of first and second year.",
        prizes:"TBD",
        image:"../../assets/images/Tinker_It.png",
        srcDoc:"https://docs.google.com/document/d/1FYxlIl67mvIraHeyXN_cR0E-l-TPF9lq_YpG3RWJUZc/edit?usp=sharing",
        srcReg:"https://dare2compete.com/competition/tinker-it-roboweek-20-national-institute-of-technology-nit-hamirpur-263696"
    },
    {
      id: 11,
      emoji: "💪",
      name: "squiz",
      instructions:
        "Participants have to answer general robotics and tech related questions.",
        instructions2:"30 questions should be be answered in 20 min time.",
        instructions3:"MCQ Fill in the blanks and picture based question will be asked 1 Round only.",
        instructions4:"",
        instructions5:"",
        title:"Squiz game",
        submission1:"Submission platform- Google Forms .",
        submission2:"The submission window will be open from 26/03/2022  9 P.M. to 9:30 P.M.",
        judging1:"Based on the no of correct answers the score will be distributed.",
        judging2:" In case of tie breaker the participant who submitted the form in less time will be considered as winner.",
        judging3:"",
        prerequisites:"All you need is general knowledge in the field of robotics and technology.",
        prizes:"TBD",
        image:"../../assets/images/squiz.png",
        srcDoc:"https://docs.google.com/document/d/1VADtDVxVw2ZtXwP_3npkTg64_P5pjRo5g4IsgvDaHaA/edit?usp=sharing",
        srcReg:"https://dare2compete.com/quiz/squiz-game-roboweek-20-national-institute-of-technology-nit-hamirpur-262825"
    }
  ];
  
  
  export default homedata